#Create a job which will run a container which sleeps for three seconds then stops.
apiVersion: batch/v1
kind: Job
metadata:
    name: sleepy
spec:
    template:
        spec:
            containers:
            - name: resting
              image: busybox
              command: ["/bin/sleep"]
              args: ["3"]
            restartPolicy: Never